version: '1.0'

services:
    Website1:
        image: ghcr.io/samoht89/website1:latest
        deploy:
            Labels:
                com.centurylinklabs.watchtower.enable: "true"
        container_name: website1 
        restart: always
        ports:
            - "80:80"
